In [8]:
print('你好！')

你好！


In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
a = pd.Series([1,3,5,np.nan,6,8])

In [12]:
a

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [20]:
dates = pd.date_range('20160808',periods=5)

In [21]:
dates

DatetimeIndex(['2016-08-08', '2016-08-09', '2016-08-10', '2016-08-11',
               '2016-08-12'],
              dtype='datetime64[ns]', freq='D')

In [25]:
df = pd.DataFrame(np.random.randn(5,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2016-08-08  0.104163  0.860834  0.824373 -0.105367
2016-08-09  0.499185 -1.982575 -0.088514  0.038605
2016-08-10  1.365384  1.161554  0.405018  0.026579
2016-08-11 -0.679043  0.106644 -1.886225  1.065234
2016-08-12 -0.182704  0.475903  0.122898  0.928639

In [26]:
df.head()

A         B         C         D
2016-08-08  0.104163  0.860834  0.824373 -0.105367
2016-08-09  0.499185 -1.982575 -0.088514  0.038605
2016-08-10  1.365384  1.161554  0.405018  0.026579
2016-08-11 -0.679043  0.106644 -1.886225  1.065234
2016-08-12 -0.182704  0.475903  0.122898  0.928639

In [27]:
df.head(1)

A         B         C         D
2016-08-08  0.104163  0.860834  0.824373 -0.105367

In [28]:
df.tail(2)

A         B         C         D
2016-08-11 -0.679043  0.106644 -1.886225  1.065234
2016-08-12 -0.182704  0.475903  0.122898  0.928639

In [29]:
df.describe()

A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.221397  0.124472 -0.124490  0.390738
std    0.770342  1.243105  1.042464  0.558349
min   -0.679043 -1.982575 -1.886225 -0.105367
25%   -0.182704  0.106644 -0.088514  0.026579
50%    0.104163  0.475903  0.122898  0.038605
75%    0.499185  0.860834  0.405018  0.928639
max    1.365384  1.161554  0.824373  1.065234

In [30]:
df.T

2016-08-08  2016-08-09  2016-08-10  2016-08-11  2016-08-12
A    0.104163    0.499185    1.365384   -0.679043   -0.182704
B    0.860834   -1.982575    1.161554    0.106644    0.475903
C    0.824373   -0.088514    0.405018   -1.886225    0.122898
D   -0.105367    0.038605    0.026579    1.065234    0.928639

In [32]:
df.sort_values(by='C')

A         B         C         D
2016-08-11 -0.679043  0.106644 -1.886225  1.065234
2016-08-09  0.499185 -1.982575 -0.088514  0.038605
2016-08-12 -0.182704  0.475903  0.122898  0.928639
2016-08-10  1.365384  1.161554  0.405018  0.026579
2016-08-08  0.104163  0.860834  0.824373 -0.105367

In [33]:
3/2

1.5

In [1]:
import numpy as np

In [2]:
arr = np.array([[1.0,2.0,3.0],[4.,5.,6.]])

In [3]:
print(arr*arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [4]:
print(arr-arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(1/arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [8]:
print(arr**0.5)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [1]:
#书

In [14]:
import numpy as np

In [15]:
my_arr = np.arange(1000000)

In [16]:
my_list = list(range(1000000))

In [17]:
%time for _ in range(10):my_arr2 = my_arr *2

Wall time: 31.2 ms


In [3]:
%time for _ in range(10):my_list2 = [x * 2 for in my_list]

SyntaxError: invalid syntax (<unknown>, line 1)

In [3]:
import numpy as np

In [4]:
data = np.random.randn(2,3)

In [5]:
data

array([[ 1.99132226, -0.31991934,  0.40021481],
       [-1.56449269, -0.82455327, -0.70763971]])

In [6]:
data*10

array([[ 19.91322257,  -3.19919345,   4.00214812],
       [-15.64492686,  -8.24553272,  -7.07639707]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [1]:
data1 = [6.,7.5,8.0,1]

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([6. , 7.5, 8. , 1. ])

In [6]:
data2 = [1,2,3,4],[5,6,7,8]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2,3,2))

array([[[6.62636825e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.24610383e-306, 6.82116729e-043]],

       [[4.22086902e-090, 2.62648363e+179],
        [4.28997637e-038, 6.59450945e-066],
        [3.99910963e+252, 2.57078601e+184]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)

In [26]:
arr1.dtype


dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)

In [30]:
float_arr.dtype

dtype('float64')

In [31]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [32]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [33]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)

In [34]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype = np.float64)

In [36]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [38]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
arr**0.2

array([[1.        , 1.14869835, 1.24573094],
       [1.31950791, 1.37972966, 1.43096908]])

In [45]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [46]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [47]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [48]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[5]

5

In [50]:
arr[5:8]

array([5, 6, 7])

In [51]:
arr[5:8]= 12

In [52]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [53]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [54]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [55]:
arr_slice[:]=64

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
arr2d[2]

array([7, 8, 9])

In [59]:
arr2d[0][2]

3

In [60]:
arr2d[0,2]

3

In [61]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
old_values = arr3d[0].copy()

In [64]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])